pool:
  vmImage: ubuntu-16.04
variables:
- name: nlw_token
  value: 6953114f33e88c5cea935c117d88d5928f53db0c956844c2
- name: PYTHONUNBUFFERED
  value: 1
stages:
- stage: __default
  jobs:
  - job: RunLoadTest
    displayName: Run NeoLoad Test from Azure Devops
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: 3.8
    - task: Bash@3
      displayName: Install NeoLoad CLI
      continueOnError: false
      inputs:
        targetType: inline
        script: >
          pip install neoload
    - task: Bash@3
      displayName: Run the NeoLoad test
      continueOnError: true
      inputs:
        targetType: inline
        script: >
          neoload login $(nlw_token)

          neoload run --name "Azure CI version $(Build.BuildNumber)" --description "Azure example with meta; $(Build.BuildUri)" "AZURE_PYTHON"
    - task: Bash@3
      displayName: get the junits SLA
      continueOnError: true
      inputs:
        targetType: inline
        script: >
          neoload test-results --junit-file $(Common.TestResultsDirectory)/neoload-slas.xml junitsla
    - task: PublishTestResults@2
      displayName: publish test results
      inputs:
        testResultsFormat: JUnit
        testResultsFiles: $(Common.TestResultsDirectory)/neoload-slas.xml
        failTaskOnFailedTests: true

